# Generated by Django 4.2.4 on 2023-08-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('field_of_study', models.CharField(max_length=200)),
                ('year_of_study', models.IntegerField()),
                ('status', models.CharField(choices=[('session', 'In Session'), ('holiday', 'On Holiday')], max_length=30)),
            ],
        ),
    ]
